DROP PROCEDURE IF EXISTS p1;

delimiter $$

CREATE PROCEDURE p1(
	NAME VARCHAR(4000),
	PHONENUMBER INT
)

BEGIN 
	DECLARE `V_FUNCTION_NAME` VARCHAR(50) DEFAULT 'Process Charge response';
	DECLARE `V_CRAETED`       VARCHAR(40) DEFAULT 'RealTime';

DECLARE EXIT HANDLER FOR SQLEXCEPTION, NOT FOUND, SQLWARNING
	 BEGIN
	 GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,  @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
    SET @full_error = CONCAT("GLOBAL ERROR : ", @errno, " (", @sqlstate, "): ", @TEXT);
    SELECT @full_error;
    RESIGNAL;
	 END;
 BEGIN
 	
 	DECLARE EXIT HANDLER FOR SQLEXCEPTION, NOT FOUND, SQLWARNING
	 BEGIN
	 GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,  @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
    SET @full_error = CONCAT("ERROR PGTABLE : ", @errno, " (", @sqlstate, "): ", @TEXT);
    SELECT @full_error;
	 END;
 	INSERT INTO pg_table VALUES (NEXTVAL(PG_2_SG_SEQUENCE), `NAME`, `PHONENUMBER`, `V_FUNCTION_NAME`, `V_CRAETED`);
	SELECT * FROM pg_table;
 END;
 
 BEGIN
 --	DROP TABLE XXXX;
 -- CREATE SEQUENCE PG_2_SG_SEQUENCE START WITH 1 INCREMENT BY 1 MINVALUE=1 MAXVALUE=999999999999999;
 END;
 
END;$$

DELIMITER ;

